# Generated by Django 2.2.9 on 2020-01-29 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atk_choice', models.CharField(choices=[('', ''), ('Rock', 'Rock'), ('Scissors', 'Scissors'), ('Paper', 'Paper')], default='Rock', max_length=10)),
                ('dfs_choice', models.CharField(choices=[('', ''), ('Rock', 'Rock'), ('Scissors', 'Scissors'), ('Paper', 'Paper')], default='Rock', max_length=10)),
                ('result', models.CharField(max_length=50)),
                ('atk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacker', to=settings.AUTH_USER_MODEL)),
                ('dfn_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
